default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: simple_chat_development

test:
  <<: *default
  database: simple_chat_test

production:
  <<: *default
  pool: <%= ENV.fetch('DATABASE_POOL',25) %>
